### ISSUE TITLE
Error: logger.status is not a function

### ISSUE THREAD

**Issue by jahredhope** [mugi-uno/parcel-plugin-bundle-manifest#14]
I receive the following error when creating a new build with Parcel, adding only `parcel-plugin-bundle-manifest` and basic entry files.

>  logger.status is not a function
    at Bundler.bundler.on (node_modules/parcel-plugin-bundle-manifest/plugins/BundleManifestPlugin.js:54:12)
    at Bundler.emit (events.js:182:13)
    at Bundler.bundle (node_modules/parcel-bundler/src/Bundler.js:300:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Package | Version
----|----
`parcel-bundler` | 1.9.6
`parcel-plugin-bundle-manifest`| 0.1.2

# Likely Cause
[parcel-bundler v1.9.5 ](https://github.com/parcel-bundler/parcel/blob/master/CHANGELOG.md#195---2018-07-11) added improvements to the Logger.

[A part of the change](https://github.com/parcel-bundler/parcel/pull/1472/files) appears to be to deprecate `Logger.status` in favour of `Logger.progress`.
[Logger.status is used](https://github.com/mugi-uno/parcel-plugin-bundle-manifest/blob/d87b3dd24b0b46c6361626d0f0764eaabc6c7718/plugins/BundleManifestPlugin.js#L19) by this package. 

# Workaround
Downgrading to `parcel-bundler` v1.9.4 solves the issue.

This issue will likely be solved by https://github.com/mugi-uno/parcel-plugin-bundle-manifest/pull/13

**Comment by mugi-uno** [comment]
fix by #15
